<?php
$t_columns = [
'id',
'project_id',
'reporter_id',
'handler_id',
'priority',
'severity',
'reproducibility',
'version',
'category_id',
'date_submitted',
'os',
'os_build',
'platform',
'view_state',
'last_updated',
'summary',
'status',
'resolution',
'fixed_in_version',
'custom_unite',
'custom_date clôture',
'custom_Saisie directe',
'custom_Numéro WorkItem TFS (WI)',
'custom_Code clôture (uniquement pour les FFT "support")',
'custom_Téléphone',
'custom_Annulé',
'custom_Ensemble de modifications (TFS, GIT,...)',
'custom_Numéro de build (Jenkins)'
];

$all_columns = [
'id',
'project_id',
'reporter_id',
'handler_id',
'priority',
'severity',
'reproducibility',
'status',
'resolution',
'category_id',
'date_submitted',
'last_updated',
'os',
'os_build',
'platform',
'version',
'fixed_in_version',
'target_version',
'view_state',
'summary',
'due_date',
'description',
'steps_to_reproduce',
'additional_information',
'attachment_count',
'bugnotes_count',
'selection',
'edit',
'notes',
'tags',
'overdue',
'custom_Annulé',
'custom_Code clôture (uniquement pour les FFT "support")',
'custom_Date clôture',
'custom_Ensemble de modifications (TFS, GIT,...)',
'custom_Numéro de build (Jenkins)',
'custom_Numéro WorkItem TFS (WI)',
'custom_Saisie directe',
'custom_Unité'
];

$xl_columns = [
'id',
'last_updated',
'status',
'version',
'target_version',
'severity',
'priority',
'category_id',
'summary',
'description',
'reproducibility',
'additional_information',
'custom_Date clôture',
'custom_Unité',
];

$column_titles = array(
'id' => 'Réf',
'project_id' => 'Projet',
'reporter_id' => 'Reporteur',
'handler_id' => 'Assigné à',
'priority' => 'Criticité',
'severity' => 'Impact',
'reproducibility' => 'Reproductibilité',
'version'  => 'Version',
'category_id' => 'Qualification',
'date_submitted' => 'Date création',
'os'  => 'OS',
'os_build' => 'Build OS',
'platform' => 'Plate-forme',
'view_state' => 'view_state',
'last_updated' => 'Date MAJ',
'summary' => 'Résumé',
'status' => 'Statut',
'resolution' => 'Résolution',
'target_version' => 'Version ciblée',
'custom_unite' => 'Unité',
'custom_date clôture' => 'Date de clôture',
'custom_Saisie directe' => 'Saisie directe',
'custom_Numéro WorkItem TFS (WI)' => 'WorkItem TFS',
'custom_Code clôture (uniquement pour les FFT "support")' => 'Code clôture',
'custom_Téléphone' => 'Téléphone',
'custom_Annulé' => 'Annulé',
'custom_Ensemble de modifications (TFS, GIT,...)' => 'Modifications (TFS/GIT)',
'custom_Numéro de build (Jenkins)' => 'Build Jenkins',
'edit' => 'Edition',
'notes' => 'Notes',
'tags' => 'Tags',
'overdue' => 'Retard',
'due_date' => 'Date cible',
'steps_to_reproduce' => 'Etapes pour reproduire',
'additional_information' => 'Infos supplémentaires',
'attachment_count' => 'Nb. pièces jointes',
'bugnotes_count' => 'Nb. notes',
);

?>